language: python
python:
  - 2.7
  - 3.3
  - 3.4
install: 
  - pip install future
  - pip install six
  - pip install NetworkManager
  - pip install SimpleCV
script:
  - nosetests --with-coverage
script:
  - nosetests --with-cov --cover-package pysec --logging-level=INFO
after_success:
  - coveralls